
alias ls='ls -la --color=auto'
alias free='LANG=C free'
alias cgrep='grep -rin --include=*.{h,c,cpp,cxx}'
alias hgrep='grep -rin --include=*.{h,hc,hpp,hxx}'
alias sysprc='sudo sysquery -prc'
alias syslog='journalctl -b -f --lines=300'
